# Generated by Django 2.1 on 2019-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=250, upload_to='', width_field=350)),
                ('Ac_Brand', models.CharField(max_length=35)),
                ('Info', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=5)),
            ],
        ),
    ]
