# Generated by Django 2.1 on 2019-06-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGApp', '0002_auto_20190616_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ac_list',
        ),
    ]
