# Generated by Django 2.1 on 2019-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SGApp', '0003_delete_ac_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='AClist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Info', models.CharField(max_length=90)),
                ('Rating', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
