# Generated by Django 2.1 on 2019-06-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGApp', '0004_aclist'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclist',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
