# Generated by Django 2.1 on 2019-07-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGApp', '0007_auto_20190704_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='phone',
            new_name='Phone',
        ),
    ]
