# Generated by Django 2.1 on 2019-07-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGApp', '0008_auto_20190704_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Brand',
            field=models.CharField(choices=[('samsung', 'Samsung'), (12, 'LG'), (13, 'Lloyd'), (14, 'Hitachi'), (15, 'Voltas'), (16, 'BlueStar'), (17, 'Haier'), (18, 'Daikin'), (19, 'Carrier'), (20, 'Mitsubishi')], default='Samsung', max_length=15),
        ),
    ]
