# Generated by Django 2.1 on 2019-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGApp', '0009_auto_20190704_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Brand',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('lg', 'LG'), ('lloyd', 'Lloyd'), ('hitachi', 'Hitachi'), ('voltas', 'Voltas'), ('bluestar', 'BlueStar'), ('haier', 'Haier'), ('daikin', 'Daikin'), ('carrier', 'Carrier'), ('mitstubishi', 'Mitsubishi')], default='Samsung', max_length=15),
        ),
    ]
